vscode:
  extensions:
    - gluons.vscode-atom-javascript-snippet@0.2.1:I19qhtAZMl2HST6uPhOeiQ==
    - lihui.vs-color-picker@1.0.0:hzx9jPABxr2kCAYpdSUNcA==
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
    - tungvn.wordpress-snippet@1.1.5:7Z4nUZ1Dm7u/jPdJWqueqQ==
    - medzhidov.font-awesome-codes-html@0.0.7:/jYopCGZaPZkD0Vx7kJReg==
    - smelukov.vscode-csstree@0.8.0:4ZjC/hYRdxcD6nNN9t1AnQ==
    - sburg.vscode-javascript-booster@14.0.1:VAdseHMcf1XczA6qYOn/kA==
    - ritwickdey.live-sass@3.0.0:x2c+sCJm+QmH2qn2h1X9Zw==
    - pranaygp.vscode-css-peek@3.0.2:KkppHBMdjTfFipMc2nCvFA==
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==